document.writeln("<div class=\"sideNav\" id=\"sideNav\">");
document.writeln("    <div class=\"innerWrapper fl fonts\">");
document.writeln("      <div class=\"logo\"><i></i></div>");
document.writeln("      <ul>");
document.writeln("        <li><a href=\"about.html\" title=\"医院简介\">医院简介</a></li>");
document.writeln("        <li><a href=\"team.html\" title=\"医师团队\">医师团队</a></li>");
document.writeln("        <li><a href=\"/hfyjy/smyq/\" title=\"设备体系\">设备体系</a></li>");
document.writeln("        <li><a href=\"news.html?\" title=\"壹美新闻\">壹美新闻</a></li>");
document.writeln("        <li><a href=\"/hfyjy/gyhj/\" title=\"医院环境\">医院环境</a></li>");
document.writeln("        <li><a href=\"/hfyjy/lylx.html\" title=\"来院路线\">来院路线</a></li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("</div>");